### ISSUE TITLE
Datasheet link broken for LCD Panel

### ISSUE THREAD

**Issue by masl123** [dchwebb/Oscar#3]
Hey, 
I'm interested in building the module. I will do some of the fixes mentioned in the schematic... Notably the easy ones like adding capacitors to the Opamps and Resistor to Boot0 and also maybe the optos for the midi connection....

Sadly the Datasheet Link ([this one](http://pan.baidu.com/s/11Y990)) for the LCD screen in the schematic is broken and there seems to be no information about the exact dimensions of the Screen available anywhere else.

I tried to identify which screen is needed: There are two sizes of LCDs with the IL9341 available that have an 18-Pin connection and might fit: 2.4 and 2.8 inch (see [2.4 inch aliexpress](https://www.aliexpress.com/item/32808378937.html) or [2.8 inch aliexpress](https://www.aliexpress.com/item/1005007014087481.html)). Which is the correct one? Note: Both offers have the dimensions in the listing.

Another Question: Did you only buy the Panels (like in the above listings) or did you get one of those "cheap" PCBs with a Panel already soldered onto it and removed the Panel somehow?

**Comment by dchwebb** [comment]
The correct version is the 2.4 inch with 4 wire SPI connection. Eg:

https://www.ebay.co.uk/itm/394725476377
https://www.ebay.co.uk/itm/155133297926

The one in the first aliexpress link above also looks correct.

I'm not sure I would bother with the opto-coupler for the MIDI in as the MIDI function is just diagnostic, so any noise introduced from the ground line can just be solved by unplugging it. 

However you may want to redesign the MIDI connection as I designed it before the MIDI over TRS was standardised. If you use a proper TRS socket (Eg the PJ366ST at https://www.thonk.co.uk/shop/thonkiconn/ ) then I would connect the tip to the MIDI input and the sleeve to ground. The ring should be left floating. That will conform to the new MIDI standard.
